### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by t-bltg**
Is everyone ok with a new version ?

It's debatable whether making `Pluto` optional requires a minor or patch bump, I'm ok with both.

### CODE REVIEW

**Review by Dsantra92 — CHANGES_REQUESTED** [review]
This is a breaking change, should be at least a minor bump.

I was planning for a release after adding Pluto.jl tests. But tests are far from done and I am currently too occupied to work on that. So let's make a release now.

But there are some currently grammatical mistakes in the Pluto.jl docs. We will rebase and merge this pr after we fix the docs?

**Comment by t-bltg** [comment]
Thanks for commenting.

> But there are some currently grammatical mistakes in the Pluto.jl docs. We will rebase and merge this pr after we fix the docs?

What should be changed ?

**Comment by Dsantra92** [comment]
> What should be changed ?
Merge after #142 ?

**Comment by Dsantra92** [comment]
LGTM from my end.

**Comment by t-bltg** [comment]
Thanks for fixing the docs !

Maybe we should wait for @johnnychen94 approval ;)

**Comment by Dsantra92** [comment]
> Maybe we should wait for @johnnychen94 approval ;)

Yes yes!

**Review by johnnychen94 — APPROVED** [review]
Feel free to merge :)

I'm a bit inactive these days so please feel free to move on; I'll comment when I get a chance

**Review by Dsantra92 — APPROVED** [review]

**Pull request merged**
